/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myapp;

import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ikbook extends javax.swing.JFrame {

    /**
     * Creates new form ikbook
     */
    String gender;
    static int index=0;
    static String data[] =new String [100];
    CardLayout cardLayout;
    
    
    
    public ikbook() {
        initComponents();
        
        cardLayout = (CardLayout)(cardpanel.getLayout());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel_menu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane_dash = new javax.swing.JDesktopPane();
        jLabel_dashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_bookingform = new javax.swing.JLabel();
        jLabel2_s = new javax.swing.JLabel();
        jLabel3_exit = new javax.swing.JLabel();
        jLabel1_bk = new javax.swing.JLabel();
        cardpanel = new javax.swing.JPanel();
        pnlcard1 = new javax.swing.JPanel();
        jPanelfile = new javax.swing.JPanel();
        jLabel_filesearch = new javax.swing.JLabel();
        jTextFieldsearch = new javax.swing.JTextField();
        jPanelform = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_info = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jLabel_gn1 = new javax.swing.JLabel();
        jTextField_ln = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_fn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_number = new javax.swing.JTextField();
        jComboBox_occupation = new javax.swing.JComboBox();
        jButtonreset = new javax.swing.JButton();
        jButtonsave = new javax.swing.JButton();
        jPanel_info1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_price = new javax.swing.JTextField();
        jComboBox_tourlocation = new javax.swing.JComboBox();
        jTextField_amount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDatebookingdate = new com.toedter.calendar.JDateChooser();
        jDatebookeddate = new com.toedter.calendar.JDateChooser();
        jComboBox_days = new javax.swing.JComboBox();
        pnlcard2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelfile1 = new javax.swing.JPanel();
        jLabel_filesearch1 = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        jPanelform1 = new javax.swing.JPanel();
        jLabelbookeddetailsform = new javax.swing.JLabel();
        pnlcard3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(-4);
        jSplitPane2.setDividerSize(1);

        jPanel_menu.setBackground(new java.awt.Color(46, 49, 49));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(230, 733));
        jPanel_menu.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(46, 49, 49));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 5, 0, new java.awt.Color(255, 255, 0)));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jDesktopPane_dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDesktopPane_dashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDesktopPane_dashMouseExited(evt);
            }
        });

        jLabel_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dashboard.setText("Dashboard");
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setEnabled(false);
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jDesktopPane_dashLayout = new javax.swing.GroupLayout(jDesktopPane_dash);
        jDesktopPane_dash.setLayout(jDesktopPane_dashLayout);
        jDesktopPane_dashLayout.setHorizontalGroup(
            jDesktopPane_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane_dashLayout.setVerticalGroup(
            jDesktopPane_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPane_dash.setLayer(jLabel_dashboard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_dash.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane_dash)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jDesktopPane_dash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel_menu.add(jPanel3, gridBagConstraints);

        jLabel_bookingform.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_bookingform.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_bookingform.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bookingform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_bookingform.setText("Booking form");
        jLabel_bookingform.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel_bookingform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_bookingform.setOpaque(true);
        jLabel_bookingform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_bookingformMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_bookingformMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_bookingformMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 25, 0, 0);
        jPanel_menu.add(jLabel_bookingform, gridBagConstraints);

        jLabel2_s.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2_s.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2_s.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_s.setText("Settings");
        jLabel2_s.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel2_s.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_s.setOpaque(true);
        jLabel2_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_sMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2_sMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2_sMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 127;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 25, 0, 0);
        jPanel_menu.add(jLabel2_s, gridBagConstraints);

        jLabel3_exit.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_exit.setText("Exit");
        jLabel3_exit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel3_exit.setOpaque(true);
        jLabel3_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3_exitMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 25, 151, 0);
        jPanel_menu.add(jLabel3_exit, gridBagConstraints);

        jLabel1_bk.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1_bk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1_bk.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_bk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_bk.setText("Booked details");
        jLabel1_bk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel1_bk.setOpaque(true);
        jLabel1_bk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_bkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1_bkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1_bkMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 25, 0, 0);
        jPanel_menu.add(jLabel1_bk, gridBagConstraints);

        jSplitPane2.setLeftComponent(jPanel_menu);

        cardpanel.setBackground(new java.awt.Color(255, 255, 255));
        cardpanel.setLayout(new java.awt.CardLayout());

        pnlcard1.setBackground(new java.awt.Color(204, 204, 255));

        jPanelfile.setBackground(new java.awt.Color(46, 49, 49));

        jLabel_filesearch.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_filesearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_filesearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_filesearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_filesearch.setText("Search");
        jLabel_filesearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel_filesearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_filesearch.setOpaque(true);
        jLabel_filesearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_filesearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_filesearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_filesearchMouseExited(evt);
            }
        });

        jTextFieldsearch.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldsearch.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jTextFieldsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelfileLayout = new javax.swing.GroupLayout(jPanelfile);
        jPanelfile.setLayout(jPanelfileLayout);
        jPanelfileLayout.setHorizontalGroup(
            jPanelfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_filesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanelfileLayout.setVerticalGroup(
            jPanelfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfileLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanelfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelfileLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel_filesearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelform.setBackground(new java.awt.Color(0, 255, 255));
        jPanelform.setLayout(new java.awt.GridBagLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FORM");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 285, 11, 286);
        jPanelform.add(jLabel4, gridBagConstraints);

        jPanel_info.setPreferredSize(new java.awt.Dimension(320, 480));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Personal information");

        buttonGroup1.add(jRadioButtonmale);
        jRadioButtonmale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonmale.setForeground(new java.awt.Color(0, 102, 255));
        jRadioButtonmale.setText("Male");
        jRadioButtonmale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonmaleItemStateChanged(evt);
            }
        });
        jRadioButtonmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonfemale);
        jRadioButtonfemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonfemale.setForeground(new java.awt.Color(0, 102, 255));
        jRadioButtonfemale.setText("Female");
        jRadioButtonfemale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonfemaleItemStateChanged(evt);
            }
        });
        jRadioButtonfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonfemaleActionPerformed(evt);
            }
        });

        jLabel_gn1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_gn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_gn1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_gn1.setText("Gender");

        jTextField_ln.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ln.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Firstname");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Lastname");

        jTextField_fn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_fn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Phone number");

        jTextField_mail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mailActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Mail address");

        jTextField_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numberActionPerformed(evt);
            }
        });

        jComboBox_occupation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_occupation.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_occupation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Occupation", "Doctor", "lawyer", "Soldier", "Engineer", "Software developer", "Entrepreneur", "Broker", "Lecturer", "Others" }));
        jComboBox_occupation.setBorder(null);

        jButtonreset.setBackground(new java.awt.Color(0, 255, 255));
        jButtonreset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonreset.setText("Reset");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });

        jButtonsave.setBackground(new java.awt.Color(0, 255, 255));
        jButtonsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonsave.setText("Save");
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_infoLayout = new javax.swing.GroupLayout(jPanel_info);
        jPanel_info.setLayout(jPanel_infoLayout);
        jPanel_infoLayout.setHorizontalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_infoLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jRadioButtonmale))
                            .addComponent(jLabel_gn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButtonfemale))
                    .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox_occupation, javax.swing.GroupLayout.Alignment.LEADING, 0, 237, Short.MAX_VALUE)
                        .addComponent(jTextField_mail, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addComponent(jButtonsave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonreset)))
                .addGap(46, 46, 46))
        );
        jPanel_infoLayout.setVerticalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_gn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRadioButtonfemale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jRadioButtonmale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_infoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonsave))
                        .addContainerGap())))
        );

        jPanel_info1.setPreferredSize(new java.awt.Dimension(320, 480));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Tour information");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("Booking ID");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Tour Location");

        jTextField_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Price");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("No of days");

        jTextField_price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_price.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_priceActionPerformed(evt);
            }
        });

        jComboBox_tourlocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_tourlocation.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_tourlocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eiffel Tower", "Pyramid of Giza", "Statute of Liberty", "Ikogosi water spring", "Indian Ocean, Maldives", "Yankari game reserve", "Old Trafford stadium", "Wembely stadium" }));
        jComboBox_tourlocation.setBorder(null);

        jTextField_amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_amount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_amountActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Booked date");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("Booking Date");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Amount ");

        jComboBox_days.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_days.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_days.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 days", "1 week", "2 weeks", "1 month" }));
        jComboBox_days.setBorder(null);

        javax.swing.GroupLayout jPanel_info1Layout = new javax.swing.GroupLayout(jPanel_info1);
        jPanel_info1.setLayout(jPanel_info1Layout);
        jPanel_info1Layout.setHorizontalGroup(
            jPanel_info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_info1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_days, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_tourlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatebookingdate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jDatebookeddate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel_info1Layout.setVerticalGroup(
            jPanel_info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_info1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(jComboBox_tourlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(jComboBox_days, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(jDatebookingdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jDatebookeddate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel16)
                .addGap(6, 6, 6)
                .addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlcard1Layout = new javax.swing.GroupLayout(pnlcard1);
        pnlcard1.setLayout(pnlcard1Layout);
        pnlcard1Layout.setHorizontalGroup(
            pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcard1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlcard1Layout.createSequentialGroup()
                        .addComponent(jPanel_info, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_info1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
        );
        pnlcard1Layout.setVerticalGroup(
            pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcard1Layout.createSequentialGroup()
                .addComponent(jPanelfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_info, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_info1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cardpanel.add(pnlcard1, "pnlcard1");

        pnlcard2.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Mobile no", "Email", "Price", "Amount paid", "Occupation", "Tour location", "Tour date", "Date Booked", "No of days", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 255, 204));
        jScrollPane1.setViewportView(jTable1);

        jPanelfile1.setBackground(new java.awt.Color(46, 49, 49));

        jLabel_filesearch1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_filesearch1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_filesearch1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_filesearch1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_filesearch1.setText("Search");
        jLabel_filesearch1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel_filesearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_filesearch1.setOpaque(true);
        jLabel_filesearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_filesearch1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_filesearch1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_filesearch1MouseExited(evt);
            }
        });

        searchfield.setBackground(new java.awt.Color(51, 51, 51));
        searchfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchfield.setForeground(new java.awt.Color(255, 255, 255));
        searchfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));

        javax.swing.GroupLayout jPanelfile1Layout = new javax.swing.GroupLayout(jPanelfile1);
        jPanelfile1.setLayout(jPanelfile1Layout);
        jPanelfile1Layout.setHorizontalGroup(
            jPanelfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfile1Layout.createSequentialGroup()
                .addContainerGap(531, Short.MAX_VALUE)
                .addComponent(jLabel_filesearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanelfile1Layout.setVerticalGroup(
            jPanelfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfile1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanelfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelfile1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel_filesearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelform1.setBackground(new java.awt.Color(0, 255, 255));
        jPanelform1.setLayout(new java.awt.GridBagLayout());

        jLabelbookeddetailsform.setBackground(new java.awt.Color(0, 0, 0));
        jLabelbookeddetailsform.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelbookeddetailsform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelbookeddetailsform.setText("Booked Details");
        jLabelbookeddetailsform.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 285, 11, 286);
        jPanelform1.add(jLabelbookeddetailsform, gridBagConstraints);

        javax.swing.GroupLayout pnlcard2Layout = new javax.swing.GroupLayout(pnlcard2);
        pnlcard2.setLayout(pnlcard2Layout);
        pnlcard2Layout.setHorizontalGroup(
            pnlcard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelfile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlcard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(pnlcard2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanelform1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        pnlcard2Layout.setVerticalGroup(
            pnlcard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcard2Layout.createSequentialGroup()
                .addComponent(jPanelfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanelform1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(128, 128, 128))
        );

        cardpanel.add(pnlcard2, "pnlcard2");

        pnlcard3.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout pnlcard3Layout = new javax.swing.GroupLayout(pnlcard3);
        pnlcard3.setLayout(pnlcard3Layout);
        pnlcard3Layout.setHorizontalGroup(
            pnlcard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        pnlcard3Layout.setVerticalGroup(
            pnlcard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        cardpanel.add(pnlcard3, "pnlcard3");

        jSplitPane2.setRightComponent(cardpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseEntered
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel_dashboardMouseEntered

    private void jLabel_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseExited
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0,255,255)));
    }//GEN-LAST:event_jLabel_dashboardMouseExited

    private void jDesktopPane_dashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane_dashMouseEntered
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jDesktopPane_dashMouseEntered

    private void jDesktopPane_dashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane_dashMouseExited
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0,255,255)));
    }//GEN-LAST:event_jDesktopPane_dashMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3MouseEntered

    private void jLabel_bookingformMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bookingformMouseEntered
        // TODO add your handling code here:
        jLabel_bookingform.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel_bookingformMouseEntered

    private void jLabel_bookingformMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bookingformMouseExited
        // TODO add your handling code here:
        jLabel_bookingform.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0,255,255)));
    }//GEN-LAST:event_jLabel_bookingformMouseExited

    private void jLabel2_sMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_sMouseEntered
        // TODO add your handling code here:
        jLabel2_s.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel2_sMouseEntered

    private void jLabel2_sMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_sMouseExited
        // TODO add your handling code here:
        jLabel2_s.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0,255,255)));
    }//GEN-LAST:event_jLabel2_sMouseExited

    private void jLabel3_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_exitMouseEntered
        // TODO add your handling code here:
        jLabel3_exit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel3_exitMouseEntered

    private void jLabel3_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_exitMouseExited
        // TODO add your handling code here:
        jLabel3_exit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0,255,255)));
    }//GEN-LAST:event_jLabel3_exitMouseExited

    private void jLabel_bookingformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bookingformMouseClicked
        // TODO add your handling code here:
        cardLayout.show(cardpanel, "pnlcard1");
    }//GEN-LAST:event_jLabel_bookingformMouseClicked

    private void jLabel2_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_sMouseClicked
        // TODO add your handling code here:
        cardLayout.show(cardpanel, "pnlcard3");
    }//GEN-LAST:event_jLabel2_sMouseClicked

    private void jLabel1_bkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_bkMouseEntered
        // TODO add your handling code here:
        jLabel1_bk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel1_bkMouseEntered

    private void jLabel1_bkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_bkMouseExited
        // TODO add your handling code here:
        jLabel1_bk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0,255,255)));
    }//GEN-LAST:event_jLabel1_bkMouseExited

    private void jLabel1_bkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_bkMouseClicked
        // TODO add your handling code here:
         cardLayout.show(cardpanel, "pnlcard2");
    }//GEN-LAST:event_jLabel1_bkMouseClicked

    private void jLabel_filesearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearchMouseClicked

    private void jLabel_filesearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearchMouseEntered

    private void jLabel_filesearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearchMouseExited

    private void jTextField_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lnActionPerformed

    private void jTextField_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnActionPerformed

    private void jTextField_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mailActionPerformed

    private void jTextField_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numberActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
        // TODO add your handling code here:
        if (jTextField_fn.getText().equals("")||jTextField_ln.getText().equals("")||jTextField_number.getText().equals("")||jTextField_mail.getText().equals("")||jTextField_id.getText().equals("")||jTextField_price.getText().equals("")||jTextField_amount.getText().equals("")
                ||jComboBox_occupation.getSelectedItem().toString().equals("")||jComboBox_tourlocation.getSelectedItem().toString().equals("")||jComboBox_days.getSelectedItem().toString().equals("")
                ||mybookingdate() == null||mybookeddate() == null||buttonGroup1.getSelection().getActionCommand().isEmpty()
                )
        {JOptionPane.showMessageDialog(this, "Please fill in all data");}
        
        if(evt.getSource() == jButtonsave) 
        {
            data[0] = jTextField_id.getText();
            data[1] = jTextField_fn.getText();
            data[2] = jTextField_ln.getText();
            data[3] = jTextField_number.getText();
            data[4] = jTextField_mail.getText();
            
            data[5] = jTextField_price.getText();
            data[6] = jTextField_amount.getText();
            data[7] = jComboBox_occupation.getSelectedItem().toString();
            data[8] = jComboBox_tourlocation.getSelectedItem().toString();
            data[9] = jComboBox_days.getSelectedItem().toString();
            data[10] = mybookingdate();
            data[11] = mybookeddate();
            data[12] = buttonGroup1.getSelection().getActionCommand();
            
             JOptionPane.showMessageDialog(this, "Records have been saved");
             int n = JOptionPane.showConfirmDialog(this, "Do you want to add more records?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
             if(n == JOptionPane.YES_OPTION)
              {
                  index++;              
                  reset();
                          
                  System.out.println(index);
              }
              else
              {
                  this.dispose();
                  
              }
        }
        
        DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
        tblmodel.addRow(data);
    }//GEN-LAST:event_jButtonsaveActionPerformed

//    private void itemStateChanged(ItemEvent e) {
//    
//        if (e.getSource()==jRadioButtonmale) {
//             gender="male";
//             
//        }
//        else if (e.getSource()==jRadioButtonfemale) {
//             gender="female";
//        }
//        
//        else  {
//             JOptionPane.showMessageDialog(this, "select your gender");
//        }
//        
//    }
    
    public String mybookingdate() {
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-mm-dd");
            String thebookingDate = dateformat.format(jDatebookingdate.getDate());
            return thebookingDate;
       
           }
     public String mybookeddate() {
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-mm-dd");
            String thebookedDate = dateformat.format(jDatebookeddate.getDate());
            return thebookedDate;
           }
     
     
     
     public void reset() 
     {
         jTextField_id.setText(null);
         jTextField_fn.setText(null);
         jTextField_ln.setText(null);
         jTextField_number.setText(null);
         jTextField_mail.setText(null);
         jTextField_price.setText(null);
         jTextField_amount.setText(null);
         jComboBox_occupation.setSelectedIndex(0);
         jComboBox_tourlocation.setSelectedIndex(0);
         jComboBox_days.setSelectedIndex(0);
         jDatebookingdate.setCalendar(null);
         jDatebookeddate.setCalendar(null);
         buttonGroup1.clearSelection();
         searchfield.setText(null);
         
     }
    
    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_priceActionPerformed

    private void jTextField_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_amountActionPerformed

    private void jLabel_filesearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch1MouseClicked

    private void jLabel_filesearch1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch1MouseEntered

    private void jLabel_filesearch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch1MouseExited

    private void jRadioButtonfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonfemaleActionPerformed

    private void jTextFieldsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsearchActionPerformed

    private void jRadioButtonmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmaleActionPerformed

    private void jRadioButtonmaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonmaleItemStateChanged
        // TODO add your handling code here:
        jRadioButtonmale.setActionCommand("male");
        jRadioButtonfemale.setActionCommand("female");
        
        
    }//GEN-LAST:event_jRadioButtonmaleItemStateChanged

    private void jRadioButtonfemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonfemaleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonfemaleItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ikbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ikbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ikbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ikbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ikbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardpanel;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JComboBox jComboBox_days;
    private javax.swing.JComboBox jComboBox_occupation;
    private javax.swing.JComboBox jComboBox_tourlocation;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDatebookeddate;
    private com.toedter.calendar.JDateChooser jDatebookingdate;
    private javax.swing.JDesktopPane jDesktopPane_dash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel1_bk;
    private javax.swing.JLabel jLabel2_s;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_exit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_bookingform;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_filesearch;
    private javax.swing.JLabel jLabel_filesearch1;
    private javax.swing.JLabel jLabel_gn1;
    private javax.swing.JLabel jLabelbookeddetailsform;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_info;
    private javax.swing.JPanel jPanel_info1;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanelfile;
    private javax.swing.JPanel jPanelfile1;
    private javax.swing.JPanel jPanelform;
    private javax.swing.JPanel jPanelform1;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_amount;
    private javax.swing.JTextField jTextField_fn;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_ln;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_number;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextFieldsearch;
    private javax.swing.JPanel pnlcard1;
    private javax.swing.JPanel pnlcard2;
    private javax.swing.JPanel pnlcard3;
    private javax.swing.JTextField searchfield;
    // End of variables declaration//GEN-END:variables
}
