/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myapp;

import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.MutableComboBoxModel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class location extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    PreparedStatement stat;
    String selectquery;
    ResultSet rs;
    
    public location() {
               try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://IKAY\\MSSQLSERVERIK;databaseName=Library;user=sa;password=9815");
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
        initComponents();
        view();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idpanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tourfield = new javax.swing.JTextField();
        addbutton = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deletebutton = new javax.swing.JLabel();
        view = new javax.swing.JLabel();
        idpanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_tourlocation = new javax.swing.JComboBox();
        jComboBox_tourlocation1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        idpanel.setBackground(new java.awt.Color(0, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("Location");

        tourfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tourfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        tourfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourfieldActionPerformed(evt);
            }
        });
        tourfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tourfieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout idpanelLayout = new javax.swing.GroupLayout(idpanel);
        idpanel.setLayout(idpanelLayout);
        idpanelLayout.setHorizontalGroup(
            idpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tourfield, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        idpanelLayout.setVerticalGroup(
            idpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(tourfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addbutton.setBackground(new java.awt.Color(204, 204, 255));
        addbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addbutton.setText("Add");
        addbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        addbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbutton.setOpaque(true);
        addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbuttonMouseExited(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SNO", "Locations"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        deletebutton.setBackground(new java.awt.Color(204, 204, 255));
        deletebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        deletebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletebutton.setText("Delete");
        deletebutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        deletebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebutton.setOpaque(true);
        deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletebuttonMouseExited(evt);
            }
        });

        view.setBackground(new java.awt.Color(204, 204, 255));
        view.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        view.setText("View");
        view.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.setOpaque(true);
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMouseExited(evt);
            }
        });

        idpanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Location");

        jComboBox_tourlocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_tourlocation.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_tourlocation.setBorder(null);
        jComboBox_tourlocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_tourlocationItemStateChanged(evt);
            }
        });
        jComboBox_tourlocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox_tourlocationFocusLost(evt);
            }
        });
        jComboBox_tourlocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_tourlocationMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_tourlocationMouseReleased(evt);
            }
        });
        jComboBox_tourlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tourlocationActionPerformed(evt);
            }
        });
        jComboBox_tourlocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox_tourlocationKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout idpanel1Layout = new javax.swing.GroupLayout(idpanel1);
        idpanel1.setLayout(idpanel1Layout);
        idpanel1Layout.setHorizontalGroup(
            idpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_tourlocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(idpanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        idpanel1Layout.setVerticalGroup(
            idpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_tourlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jComboBox_tourlocation1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_tourlocation1.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_tourlocation1.setBorder(null);
        jComboBox_tourlocation1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_tourlocation1ItemStateChanged(evt);
            }
        });
        jComboBox_tourlocation1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox_tourlocation1FocusLost(evt);
            }
        });
        jComboBox_tourlocation1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_tourlocation1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_tourlocation1MouseReleased(evt);
            }
        });
        jComboBox_tourlocation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tourlocation1ActionPerformed(evt);
            }
        });
        jComboBox_tourlocation1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox_tourlocation1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_tourlocation1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox_tourlocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tourfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourfieldActionPerformed

    }//GEN-LAST:event_tourfieldActionPerformed

    public void showtour() 
    {
         try 
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection("jdbc:sqlserver://IKAY\\MSSQLSERVERIK;databaseName=Library;user=sa;password=9815");
                //stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                stat = con.prepareStatement("INSERT INTO tourtable VALUES(?)");
                String tfield = tourfield.getText().trim();
                
                stat.setString(1, tfield);
                
                stat.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Successful");
            } 
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null, e);
            }
     view();    
    }
    
    public void view()
    {   
            try {
            stat = con.prepareStatement("SELECT Tid as 'SNo', Tourtlo as 'Tour Location' from tourtable  ");
            rs = stat.executeQuery();
           
            
            
            while (rs.next()) {
                
                String dat[] ={String.valueOf(rs.getString("SNo")), rs.getString("Tour Location")  };
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                 DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
                 tblmodel.addRow(dat);
                
              
            }
          
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
              
    }
    
     public void viewbox()
    {   
            try {
            stat = con.prepareStatement("SELECT Tourtlo as 'Tour Location' from tourtable  ");
            rs = stat.executeQuery();
           
            
            
            while (rs.next()) {
                
                    String aa = rs.getString("Tour Location");
                    //DefaultComboBoxModel model = (DefaultComboBoxModel)jComboBox_tourlocation.getModel();
                     jComboBox_tourlocation.addItem(aa);

            }
                //con.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
              
    }
    
    public void delete()
    {
        try { 
               
           
                int row = jTable1.getSelectedRow();
                String value = (jTable1.getModel().getValueAt(row, 0).toString());
            
                int n = JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if (n == JOptionPane.YES_OPTION) 
                {
                    int y = JOptionPane.showConfirmDialog(this, "There is no going back, are you sure?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (y == JOptionPane.YES_OPTION) 
                               {

                               selectquery = "DELETE FROM tourtable WHERE Tid="+value;
                               stat = con.prepareStatement(selectquery);
                               stat.executeUpdate();
                               
                               JOptionPane.showMessageDialog(null, "Deleted");
                               view();
                               } 
                        else 
                               {
                                  JOptionPane.showMessageDialog(null, "Did not delete");
                               }
                }
                else 
                {
                   System.out.println("did not delete");
                }
                
               
            } 
           catch (SQLException ex) 
           {
                JOptionPane.showMessageDialog(null, ex);
           }           
    }
            
    private void tourfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tourfieldKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tourfieldKeyReleased

    private void addbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseClicked
        // TODO add your handling code here:
       
       showtour();

    }//GEN-LAST:event_addbuttonMouseClicked

    private void addbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonMouseEntered

    private void addbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonMouseExited

    private void deletebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseClicked
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_deletebuttonMouseClicked

    private void deletebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonMouseEntered

    private void deletebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebuttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonMouseExited

    private void jComboBox_tourlocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocationItemStateChanged

    private void jComboBox_tourlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocationActionPerformed

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        // TODO add your handling code here:
        viewbox();
    }//GEN-LAST:event_viewMouseClicked

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMouseEntered

    private void viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMouseExited

    private void jComboBox_tourlocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationFocusLost
        // TODO add your handling code here:
        jComboBox_tourlocation.removeAllItems();
    }//GEN-LAST:event_jComboBox_tourlocationFocusLost

    private void jComboBox_tourlocationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_tourlocationKeyReleased

    private void jComboBox_tourlocationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_tourlocationMouseReleased

    private void jComboBox_tourlocationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox_tourlocationMouseExited

    private void jComboBox_tourlocation1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_tourlocation1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocation1ItemStateChanged

    private void jComboBox_tourlocation1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_tourlocation1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocation1FocusLost

    private void jComboBox_tourlocation1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_tourlocation1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocation1MouseExited

    private void jComboBox_tourlocation1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_tourlocation1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocation1MouseReleased

    private void jComboBox_tourlocation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tourlocation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocation1ActionPerformed

    private void jComboBox_tourlocation1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_tourlocation1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocation1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new location().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addbutton;
    private javax.swing.JLabel deletebutton;
    private javax.swing.JPanel idpanel;
    private javax.swing.JPanel idpanel1;
    private javax.swing.JComboBox jComboBox_tourlocation;
    private javax.swing.JComboBox jComboBox_tourlocation1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField tourfield;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
