/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myapp;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class newupdate extends javax.swing.JFrame {

     Connection con;
    Statement stmt;
    PreparedStatement stat;
    String selectquery;
    ResultSet rs;
    
    public newupdate() {
        initComponents();
        
          try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://IKAY\\MSSQLSERVERIK;databaseName=Library;user=sa;password=9815");
            stmt = con.createStatement();

        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idpanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_ids = new javax.swing.JTextField();
        panelrest = new javax.swing.JPanel();
        fn = new javax.swing.JLabel();
        jTextField_fns = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_ln = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_number = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_mail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel_gn1 = new javax.swing.JLabel();
        jTextField_gn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        toutlocation = new javax.swing.JTextField();
        jTextField_dn = new javax.swing.JTextField();
        jTextField_tourdatebooked = new javax.swing.JTextField();
        jTextField_pr = new javax.swing.JTextField();
        jTextField_tourdate = new javax.swing.JTextField();
        jTextField_occu = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel_filesearch = new javax.swing.JLabel();
        updatebutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("Booking ID");

        jTextField_ids.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ids.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_ids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idsActionPerformed(evt);
            }
        });
        jTextField_ids.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_idsKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout idpanelLayout = new javax.swing.GroupLayout(idpanel);
        idpanel.setLayout(idpanelLayout);
        idpanelLayout.setHorizontalGroup(
            idpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_ids, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        idpanelLayout.setVerticalGroup(
            idpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(jTextField_ids, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fn.setForeground(new java.awt.Color(0, 102, 255));
        fn.setText("Firstname");

        jTextField_fns.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_fns.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_fns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Lastname");

        jTextField_ln.setEditable(false);
        jTextField_ln.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ln.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Phone number");

        jTextField_number.setEditable(false);
        jTextField_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numberActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Mail address");

        jTextField_mail.setEditable(false);
        jTextField_mail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mailActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Occupation");

        jLabel_gn1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_gn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_gn1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_gn1.setText("Gender");

        jTextField_gn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_gn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_gnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Tour Location");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("No of days");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Tour date");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Price");

        toutlocation.setEditable(false);
        toutlocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toutlocation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        toutlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toutlocationActionPerformed(evt);
            }
        });

        jTextField_dn.setEditable(false);
        jTextField_dn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_dn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_dn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dnActionPerformed(evt);
            }
        });

        jTextField_tourdatebooked.setEditable(false);
        jTextField_tourdatebooked.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_tourdatebooked.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_tourdatebooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tourdatebookedActionPerformed(evt);
            }
        });

        jTextField_pr.setEditable(false);
        jTextField_pr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_pr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_prActionPerformed(evt);
            }
        });

        jTextField_tourdate.setEditable(false);
        jTextField_tourdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_tourdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_tourdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tourdateActionPerformed(evt);
            }
        });

        jTextField_occu.setEditable(false);
        jTextField_occu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_occu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_occu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_occuActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("date booked");

        javax.swing.GroupLayout panelrestLayout = new javax.swing.GroupLayout(panelrest);
        panelrest.setLayout(panelrestLayout);
        panelrestLayout.setHorizontalGroup(
            panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_fns, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_gn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_gn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_occu, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelrestLayout.createSequentialGroup()
                                        .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13))
                                        .addGap(161, 161, 161))
                                    .addComponent(toutlocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_dn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_tourdatebooked, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addComponent(jTextField_tourdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel12))
                    .addComponent(jTextField_pr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelrestLayout.setVerticalGroup(
            panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelrestLayout.createSequentialGroup()
                        .addComponent(fn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_fns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_tourdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_occu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel_gn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_gn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelrestLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toutlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_dn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addComponent(jTextField_tourdatebooked, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel_filesearch.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_filesearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_filesearch.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_filesearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_filesearch.setText("Find");
        jLabel_filesearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel_filesearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_filesearch.setOpaque(true);
        jLabel_filesearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_filesearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_filesearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_filesearchMouseExited(evt);
            }
        });

        updatebutton.setBackground(new java.awt.Color(204, 204, 255));
        updatebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(255, 255, 255));
        updatebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatebutton.setText("update");
        updatebutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        updatebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebutton.setOpaque(true);
        updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatebuttonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(idpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_filesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel_filesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idsActionPerformed

    }//GEN-LAST:event_jTextField_idsActionPerformed

    private void jTextField_idsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idsKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_idsKeyReleased

    private void jTextField_fnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnsActionPerformed

    private void jTextField_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lnActionPerformed

    private void jTextField_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numberActionPerformed

    private void jTextField_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mailActionPerformed

    private void jTextField_gnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_gnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_gnActionPerformed

    private void toutlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toutlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toutlocationActionPerformed

    private void jTextField_dnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dnActionPerformed

    private void jTextField_tourdatebookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tourdatebookedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tourdatebookedActionPerformed

    private void jTextField_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_prActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_prActionPerformed

    private void jTextField_tourdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tourdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tourdateActionPerformed

    private void jTextField_occuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_occuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_occuActionPerformed
        
         public ResultSet myfunction() {
        try {
            stat = con.prepareStatement("select * from tour where tid=? ");
            stat.setString(1, jTextField_ids.getText());
            rs = stat.executeQuery();
           // rs=jTextField_ids.getText();
            
            
            if (rs.next()) {
               // jTextField_ids.setText(rs.getString("tid"));
                jTextField_fns.setText(rs.getString("tfn"));
                jTextField_ln.setText(rs.getString("tln"));
                jTextField_number.setText(rs.getString("tn"));
                jTextField_mail.setText(rs.getString("tmail"));
                jTextField_pr.setText(rs.getString("tprice"));
                jTextField_tourdate.setText(rs.getString("tbed"));
                jTextField_tourdatebooked.setText(rs.getString("tbind"));
                jTextField_dn.setText(rs.getString("tdays"));
                toutlocation.setText(rs.getString("ttlo"));
                jTextField_gn.setText(rs.getString("tbgr"));
                jTextField_occu.setText(rs.getString("toccu"));
            }
          
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
              return rs;
        }
    private void jLabel_filesearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearchMouseClicked
        // TODO add your handling code here:

        myfunction();

    }//GEN-LAST:event_jLabel_filesearchMouseClicked

    private void jLabel_filesearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearchMouseEntered

    private void jLabel_filesearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearchMouseExited

    private void updatebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseClicked
        // TODO add your handling code here:
        ikbook k = new ikbook();
//        int row = jTextField_ids.getText();
//        String value = (k.jTable1.getModel().getValueAt(row, 0).toString());
        
         try
        {
                selectquery = "UPDATE tour SET  tfn=?, tln=?, tn=?, tmail=?, tprice=?, toccu=?, ttlo=?, tdays=?, tbind=?, tbed=?, tbgr=? WHERE tid = ?";
                stat.setString(1, jTextField_ids.getText());
                stat = con.prepareStatement(selectquery);
           
               
                
                //data will be added until finish 
                
               // String id = String.valueOf(rs.getInt("tid"));
//                String fn = rs.getString("tfn");
//                String ln = rs.getString("tln");
//                String ntn = rs.getString("tn");
//                String mail = rs.getString("tmail");
//                String price = rs.getString("tPrice");
//                String occu = rs.getString("toccu");
//                String tlo = rs.getString("ttlo");
//                String days = rs.getString("tdays");
//                String bind = rs.getString("tbind");
//                String bed = rs.getString("tbed");
//                String bgr = rs.getString("tbgr"); 
                    
                String tid = jTextField_ids.getText().toLowerCase().trim();
                String tfn = jTextField_fns.getText().toLowerCase().trim();
                String tln = jTextField_ln.getText().toLowerCase().trim();
                String tn = jTextField_number.getText().toLowerCase().trim();
                String tmail = jTextField_mail.getText().toLowerCase().trim();
                String tprice = jTextField_pr.getText();
                String toccu = jTextField_occu.getText();
                String ttlo = toutlocation.getText();
                String tdays = jTextField_dn.getText();
                String tbind = jTextField_tourdatebooked.getText();
                String tbed = jTextField_tourdate.getText();
                String tbgr = jTextField_gn.getText().trim();
                    
                stat.setString(1, tid);
                stat.setString(2, tfn);
                stat.setString(3, tln);
                stat.setString(4, tn);
                stat.setString(5, tmail);
                stat.setString(6, tprice);
                stat.setString(7, toccu);
                stat.setString(8, ttlo);
                stat.setString(9, tdays);
                stat.setString(10, tbind);
                stat.setString(11, tbed);
                stat.setString(12, tbgr);
                
                        stat.executeUpdate();


                 //string array to store data in jtable
                 String  data[] = { tid, tfn, tln, tn, tmail, tprice, toccu, ttlo, tdays, tbind, tbed, tbgr};
                 k.jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                 
                 JOptionPane.showMessageDialog(null, "updated successfully");
                
               //DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
                //tblmodel.addRow(data);
        } 
            
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    }//GEN-LAST:event_updatebuttonMouseClicked

    private void updatebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonMouseEntered

    private void updatebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fn;
    private javax.swing.JPanel idpanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_filesearch;
    private javax.swing.JLabel jLabel_gn1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_dn;
    private javax.swing.JTextField jTextField_fns;
    private javax.swing.JTextField jTextField_gn;
    public javax.swing.JTextField jTextField_ids;
    public javax.swing.JTextField jTextField_ln;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_number;
    private javax.swing.JTextField jTextField_occu;
    private javax.swing.JTextField jTextField_pr;
    private javax.swing.JTextField jTextField_tourdate;
    private javax.swing.JTextField jTextField_tourdatebooked;
    private javax.swing.JPanel panelrest;
    private javax.swing.JTextField toutlocation;
    private javax.swing.JLabel updatebutton;
    // End of variables declaration//GEN-END:variables
}
