
package myapp;

import com.toedter.calendar.JDateChooser;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;



public class updateik extends javax.swing.JFrame {

       Connection con;
    Statement stmt;
    PreparedStatement stat;
    String selectquery;
    ResultSet rs;
    
    public updateik() {
           try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            con = DriverManager.getConnection("jdbc:sqlserver://IKAY\\MSSQLSERVERIK;databaseName=Library;user=sa;password=9815");
            stmt = con.createStatement();

        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
            
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel_info = new javax.swing.JPanel();
        jTextField_gn = new javax.swing.JLabel();
        jTextField_ln = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_fn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_number = new javax.swing.JTextField();
        jComboBox_occupation = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_price = new javax.swing.JTextField();
        jComboBox_tourlocation = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox_days = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        jbookingdate = new javax.swing.JTextField();
        jtourdate = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        jgender = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField_id = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mysearchbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UPDATE");
        setResizable(false);

        jPanel_info.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_info.setPreferredSize(new java.awt.Dimension(320, 480));

        jTextField_gn.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_gn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField_gn.setForeground(new java.awt.Color(0, 102, 255));
        jTextField_gn.setText("Gender");

        jTextField_ln.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ln.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Firstname");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Lastname");

        jTextField_fn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_fn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Phone number");

        jTextField_mail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mailActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Mail address");

        jTextField_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numberActionPerformed(evt);
            }
        });

        jComboBox_occupation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_occupation.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_occupation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Doctor", "lawyer", "Soldier", "Engineer", "Software developer", "Entrepreneur", "Broker", "Lecturer", "Others" }));
        jComboBox_occupation.setBorder(null);
        jComboBox_occupation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_occupationItemStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Occupation");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Tour Location");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Price");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("No of days");

        jTextField_price.setEditable(false);
        jTextField_price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_price.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_priceActionPerformed(evt);
            }
        });

        jComboBox_tourlocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_tourlocation.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_tourlocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Eiffel Tower", "Pyramid of Giza", "Statute of Liberty", "Ikogosi water spring", "Indian Ocean, Maldives", "Yankari game reserve", "Old Trafford stadium", "Wembely stadium" }));
        jComboBox_tourlocation.setBorder(null);
        jComboBox_tourlocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_tourlocationItemStateChanged(evt);
            }
        });
        jComboBox_tourlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tourlocationActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Tour date");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("Booking Date");

        jComboBox_days.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_days.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_days.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "3 days", "1 week", "2 weeks", "1 month" }));
        jComboBox_days.setBorder(null);

        search.setBackground(new java.awt.Color(0, 255, 255));
        search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search.setText("Total");
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jbookingdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbookingdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jbookingdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbookingdateActionPerformed(evt);
            }
        });

        jtourdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtourdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jtourdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtourdateActionPerformed(evt);
            }
        });

        updatebutton.setBackground(new java.awt.Color(0, 255, 255));
        updatebutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebuttonMouseClicked(evt);
            }
        });
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        jgender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jgender.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgenderActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jTextField_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("Booking ID");

        mysearchbutton.setBackground(new java.awt.Color(0, 255, 255));
        mysearchbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mysearchbutton.setText("Find");
        mysearchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mysearchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mysearchbuttonMouseClicked(evt);
            }
        });
        mysearchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mysearchbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(mysearchbutton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mysearchbutton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_infoLayout = new javax.swing.GroupLayout(jPanel_info);
        jPanel_info.setLayout(jPanel_infoLayout);
        jPanel_infoLayout.setHorizontalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_gn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox_occupation, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_mail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jgender))
                .addGap(141, 141, 141)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtourdate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbookingdate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_days, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_tourlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_infoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_infoLayout.createSequentialGroup()
                        .addComponent(updatebutton)
                        .addGap(308, 308, 308))))
        );
        jPanel_infoLayout.setVerticalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(1, 1, 1)
                        .addComponent(jComboBox_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_gn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox_tourlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox_days, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9)
                        .addComponent(jbookingdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtourdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jgender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatebutton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_info, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_info, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lnActionPerformed

    private void jTextField_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnActionPerformed

    private void jTextField_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mailActionPerformed

    private void jTextField_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numberActionPerformed

    private void jComboBox_occupationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_occupationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_occupationItemStateChanged

    private void updatebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonMouseClicked

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
//        String id = String.valueOf(rs.getInt("tid"));
//                String fn = rs.getString("tfn");
//                String ln = rs.getString("tln");
//                String ntn = rs.getString("tn");
//                String mail = rs.getString("tmail");
//                String price = rs.getString("tPrice");
//                String occu = rs.getString("toccu");
//                String tlo = rs.getString("ttlo");
//                String days = rs.getString("tdays");
//                String bind = rs.getString("tbind");
//                String bed = rs.getString("tbed");
//                String bgr = rs.getString("tbgr"); 
        ikbook k = new ikbook();
        
        
         try
        {
                selectquery = "update mynewtour SET Tourfn=?, Tourln=?, Tournumber=?, Tourmail=?, Tourprice=?, Touroccu=?, Tourtlo=?, Tourdays=?, Tourbind=?, Tourbed=?, Tourbgr=? where Tourid="+ jTextField_id.getText() ;
                //stat.setString(1, jTextField_id.getText());
                stat = con.prepareStatement(selectquery);
               
               
                
                //data will be added until finish 
                
                
                String tfn = jTextField_fn.getText().toLowerCase().trim();
                String tln = jTextField_ln.getText().toLowerCase().trim();
                int tn  = Integer.parseInt(jTextField_number.getText().toLowerCase().trim());
                String tmail = jTextField_mail.getText().toLowerCase().trim();
                int tprice = Integer.parseInt(jTextField_price.getText().trim());
                String toccu = jComboBox_occupation.getSelectedItem().toString();
                String ttlo = jComboBox_tourlocation.getSelectedItem().toString();
                String tdays = jComboBox_days.getSelectedItem().toString();
                String tbind = jbookingdate.getText().toLowerCase().trim();
                String tbed = jtourdate.getText().toLowerCase().trim();
                String tbgr = jgender.getText().toLowerCase().trim();
                String tid = jTextField_id.getText().toLowerCase().trim();

                
                stat.setString(1, tfn);
                stat.setString(2, tln);
                stat.setInt(3, tn);
                stat.setString(4, tmail);
                stat.setInt(5, tprice);
                stat.setString(6, toccu);
                stat.setString(7, ttlo);
                stat.setString(8, tdays);
                stat.setString(9, tbind);
                stat.setString(10, tbed);
                stat.setString(11, tbgr);
                //stat.setString(12, tid);
                
                 stat.execute();


                 //string array to store data in jtable
                 //String  data[] = { tfn, tln, tn, tmail, tprice, toccu, ttlo, tdays, tbind, tbed, tbgr};
                 k.jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                 
                 JOptionPane.showMessageDialog(null, "updated successfully");
                
               //DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
                //tblmodel.addRow(data);
        } 
            
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void jgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jgenderActionPerformed

    private void mysearchbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mysearchbuttonMouseClicked
        // TODO add your handling code here:
         try {
            stat = con.prepareStatement("select * from mynewtour where Tourid=? ");
            stat.setString(1, jTextField_id.getText());
            rs = stat.executeQuery();
           // rs=jTextField_ids.getText();
            
            
            if (rs.next()) {
               // jTextField_ids.setText(rs.getString("Tourid"));
                jTextField_fn.setText(rs.getString("Tourfn"));
                jTextField_ln.setText(rs.getString("Tourln"));
                jTextField_number.setText(String.valueOf(rs.getString("Tournumber")));
                jTextField_mail.setText(rs.getString("Tourmail"));
                jTextField_price.setText(String.valueOf(rs.getString("Tourprice")));
                jtourdate.setText(rs.getString("Tourbed"));
                jbookingdate.setText(rs.getString("Tourbind"));
                jComboBox_days.setSelectedItem(rs.getString("Tourdays"));
                jComboBox_tourlocation.setSelectedItem(rs.getString("Tourtlo"));
                jgender.setText(rs.getString("Tourbgr"));
                jComboBox_occupation.setSelectedItem(rs.getString("Touroccu"));
            }
          
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_mysearchbuttonMouseClicked

    private void mysearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mysearchbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mysearchbuttonActionPerformed

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jtourdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtourdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtourdateActionPerformed

    private void jbookingdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbookingdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbookingdateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        int eiffel = 150000;
        int pyramid = 200000;
        int statute = 180000;
        int ikogosi = 100000;
        int indian = 220000;
        int yankari = 120000;
        int trafford = 300000;
        int wembely = 300000;

        int days = 50000;
        int week = 100000;
        int weeks = 150000;
        int month = 200000;

        int result;

        //eiffel
        if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = eiffel + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = eiffel + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = eiffel + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = eiffel + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //pyramid
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = pyramid + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = pyramid + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = pyramid + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = pyramid + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //statute
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = statute + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = statute + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = statute + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = statute + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //ikogosi
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = ikogosi + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = ikogosi + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = ikogosi + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = ikogosi + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //indian ocean
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = indian + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = indian + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = indian + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = indian + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //yankari reserve
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = yankari + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = yankari + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = yankari + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = yankari + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //old trafford
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = trafford + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = trafford + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = trafford + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = trafford + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //wembely
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = wembely + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = wembely + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = wembely + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = wembely + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        }
    }//GEN-LAST:event_searchMouseClicked

    private void jComboBox_tourlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocationActionPerformed

    private void jComboBox_tourlocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocationItemStateChanged

    private void jTextField_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox jComboBox_days;
    private javax.swing.JComboBox jComboBox_occupation;
    private javax.swing.JComboBox jComboBox_tourlocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_info;
    private javax.swing.JTextField jTextField_fn;
    private javax.swing.JLabel jTextField_gn;
    private javax.swing.JTextField jTextField_id;
    public javax.swing.JTextField jTextField_ln;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_number;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jbookingdate;
    private javax.swing.JTextField jgender;
    private javax.swing.JTextField jtourdate;
    private javax.swing.JButton mysearchbutton;
    private javax.swing.JButton search;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
