/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myapp;

import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static myapp.ikbook.index;
import net.proteanit.sql.DbUtils;

public class user extends javax.swing.JFrame

{
    String gender;
    //String data[][];
    
    
    static int index = 1;
    
    int newindex = 0;
    CardLayout cardLayout;
    Connection con;
    Statement stmt; 
    PreparedStatement stat;
    String selectquery;
    ResultSet rs;

    
    public user() {
        initComponents();
        
        cardLayout = (CardLayout) (cardpanel.getLayout());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel_menu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane_dash = new javax.swing.JDesktopPane();
        jLabel_dashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_bookingform = new javax.swing.JLabel();
        jLabel2_s = new javax.swing.JLabel();
        jLabel3_exit = new javax.swing.JLabel();
        jLabel1_bk = new javax.swing.JLabel();
        cardpanel = new javax.swing.JPanel();
        pnlcard1 = new javax.swing.JPanel();
        jPanelfile = new javax.swing.JPanel();
        searchbutton = new javax.swing.JLabel();
        updatebutton = new javax.swing.JLabel();
        jPanelform = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_info = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jLabel_gn1 = new javax.swing.JLabel();
        jTextField_ln = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_fn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_number = new javax.swing.JTextField();
        jComboBox_occupation = new javax.swing.JComboBox();
        jButtonreset = new javax.swing.JButton();
        jButtonsave = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel_info1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_price = new javax.swing.JTextField();
        jComboBox_tourlocation = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDatebookingdate = new com.toedter.calendar.JDateChooser();
        jDatebookeddate = new com.toedter.calendar.JDateChooser();
        jComboBox_days = new javax.swing.JComboBox();
        jButtontotal = new javax.swing.JButton();
        pnlcard2 = new javax.swing.JPanel();
        jPanelfile1 = new javax.swing.JPanel();
        jLabel_filesearch1 = new javax.swing.JLabel();
        jPanelform1 = new javax.swing.JPanel();
        jLabelbookeddetailsform = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlcard3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        myreceipt4 = new javax.swing.JTextArea();
        receipt_button4 = new javax.swing.JLabel();
        jPanelform6 = new javax.swing.JPanel();
        jLabelbookeddetailsform5 = new javax.swing.JLabel();
        jPanelfile3 = new javax.swing.JPanel();
        jLabel_filesearch3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLERK'S FORM");

        jSplitPane2.setDividerLocation(-4);
        jSplitPane2.setDividerSize(1);

        jPanel_menu.setBackground(new java.awt.Color(46, 49, 49));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(230, 733));

        jPanel3.setBackground(new java.awt.Color(46, 49, 49));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 5, 0, new java.awt.Color(255, 255, 0)));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jDesktopPane_dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDesktopPane_dashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDesktopPane_dashMouseExited(evt);
            }
        });

        jLabel_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dashboard.setText("Dashboard");
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setEnabled(false);
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jDesktopPane_dashLayout = new javax.swing.GroupLayout(jDesktopPane_dash);
        jDesktopPane_dash.setLayout(jDesktopPane_dashLayout);
        jDesktopPane_dashLayout.setHorizontalGroup(
            jDesktopPane_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane_dashLayout.setVerticalGroup(
            jDesktopPane_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPane_dash.setLayer(jLabel_dashboard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane_dash.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane_dash)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jDesktopPane_dash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel_bookingform.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_bookingform.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_bookingform.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bookingform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_bookingform.setText("Booking form");
        jLabel_bookingform.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel_bookingform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_bookingform.setOpaque(true);
        jLabel_bookingform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_bookingformMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_bookingformMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_bookingformMouseExited(evt);
            }
        });

        jLabel2_s.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2_s.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2_s.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_s.setText("Receipt");
        jLabel2_s.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel2_s.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_s.setOpaque(true);
        jLabel2_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_sMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2_sMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2_sMouseExited(evt);
            }
        });

        jLabel3_exit.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_exit.setText("Exit");
        jLabel3_exit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel3_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3_exit.setOpaque(true);
        jLabel3_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3_exitMouseExited(evt);
            }
        });

        jLabel1_bk.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1_bk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1_bk.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_bk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_bk.setText("Booked details");
        jLabel1_bk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel1_bk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_bk.setOpaque(true);
        jLabel1_bk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_bkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1_bkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1_bkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_bookingform, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_bk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_s, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel_bookingform, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1_bk, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel2_s, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel_menu);

        cardpanel.setBackground(new java.awt.Color(255, 255, 255));
        cardpanel.setLayout(new java.awt.CardLayout());

        pnlcard1.setBackground(new java.awt.Color(204, 204, 255));

        jPanelfile.setBackground(new java.awt.Color(46, 49, 49));

        searchbutton.setBackground(new java.awt.Color(51, 51, 51));
        searchbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 255));
        searchbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchbutton.setText("Search");
        searchbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        searchbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbutton.setOpaque(true);
        searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbuttonMouseExited(evt);
            }
        });

        updatebutton.setBackground(new java.awt.Color(51, 51, 51));
        updatebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(255, 255, 255));
        updatebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatebutton.setText("Update");
        updatebutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        updatebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebutton.setOpaque(true);
        updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatebuttonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelfileLayout = new javax.swing.GroupLayout(jPanelfile);
        jPanelfile.setLayout(jPanelfileLayout);
        jPanelfileLayout.setHorizontalGroup(
            jPanelfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanelfileLayout.setVerticalGroup(
            jPanelfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfileLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelform.setBackground(new java.awt.Color(0, 255, 255));
        jPanelform.setLayout(new java.awt.GridBagLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CLERK'S FORM");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 285, 11, 286);
        jPanelform.add(jLabel4, gridBagConstraints);

        jPanel_info.setPreferredSize(new java.awt.Dimension(320, 480));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Personal information");

        buttonGroup1.add(jRadioButtonmale);
        jRadioButtonmale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonmale.setForeground(new java.awt.Color(0, 102, 255));
        jRadioButtonmale.setText("Male");
        jRadioButtonmale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonmaleItemStateChanged(evt);
            }
        });
        jRadioButtonmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonfemale);
        jRadioButtonfemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonfemale.setForeground(new java.awt.Color(0, 102, 255));
        jRadioButtonfemale.setText("Female");
        jRadioButtonfemale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonfemaleItemStateChanged(evt);
            }
        });
        jRadioButtonfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonfemaleActionPerformed(evt);
            }
        });

        jLabel_gn1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_gn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_gn1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_gn1.setText("Gender");

        jTextField_ln.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ln.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Firstname");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Lastname");

        jTextField_fn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_fn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Phone number");

        jTextField_mail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mailActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Mail address");

        jTextField_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numberActionPerformed(evt);
            }
        });

        jComboBox_occupation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_occupation.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_occupation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Doctor", "lawyer", "Soldier", "Engineer", "Software developer", "Entrepreneur", "Broker", "Lecturer", "Others" }));
        jComboBox_occupation.setBorder(null);
        jComboBox_occupation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_occupationItemStateChanged(evt);
            }
        });

        jButtonreset.setBackground(new java.awt.Color(0, 255, 255));
        jButtonreset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonreset.setText("Reset");
        jButtonreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });

        jButtonsave.setBackground(new java.awt.Color(0, 255, 255));
        jButtonsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonsave.setText("Save");
        jButtonsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Occupation");

        javax.swing.GroupLayout jPanel_infoLayout = new javax.swing.GroupLayout(jPanel_info);
        jPanel_info.setLayout(jPanel_infoLayout);
        jPanel_infoLayout.setHorizontalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(jPanel_infoLayout.createSequentialGroup()
                                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jRadioButtonmale))
                                    .addComponent(jLabel_gn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jRadioButtonfemale))
                            .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox_occupation, javax.swing.GroupLayout.Alignment.LEADING, 0, 237, Short.MAX_VALUE)
                                .addComponent(jTextField_mail, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel_infoLayout.createSequentialGroup()
                                .addComponent(jButtonsave)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonreset)))
                        .addGap(46, 46, 46))))
        );
        jPanel_infoLayout.setVerticalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addComponent(jComboBox_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_gn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButtonfemale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButtonmale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsave)))
        );

        jPanel_info1.setPreferredSize(new java.awt.Dimension(320, 480));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Tour information");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setText("Booking ID");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setText("Tour Location");

        jTextField_id.setEditable(false);
        jTextField_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Price");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("No of days");

        jTextField_price.setEditable(false);
        jTextField_price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_price.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextField_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_priceActionPerformed(evt);
            }
        });

        jComboBox_tourlocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_tourlocation.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_tourlocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Eiffel Tower", "Pyramid of Giza", "Statute of Liberty", "Ikogosi water spring", "Indian Ocean, Maldives", "Yankari game reserve", "Old Trafford stadium", "Wembely stadium" }));
        jComboBox_tourlocation.setBorder(null);
        jComboBox_tourlocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_tourlocationItemStateChanged(evt);
            }
        });
        jComboBox_tourlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tourlocationActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setText("Tour date");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("Booking Date");

        jDatebookingdate.setDateFormatString("yyyy-MM-dd");

        jDatebookeddate.setDateFormatString("yyyy-MM-dd");

        jComboBox_days.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_days.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox_days.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "3 days", "1 week", "2 weeks", "1 month" }));
        jComboBox_days.setBorder(null);

        jButtontotal.setBackground(new java.awt.Color(0, 255, 255));
        jButtontotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtontotal.setText("Total");
        jButtontotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtontotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtontotalMouseClicked(evt);
            }
        });
        jButtontotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_info1Layout = new javax.swing.GroupLayout(jPanel_info1);
        jPanel_info1.setLayout(jPanel_info1Layout);
        jPanel_info1Layout.setHorizontalGroup(
            jPanel_info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_info1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtontotal)
                    .addComponent(jComboBox_days, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_tourlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatebookingdate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jDatebookeddate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel_info1Layout.setVerticalGroup(
            jPanel_info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_info1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(jComboBox_tourlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(jComboBox_days, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(jDatebookingdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jDatebookeddate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButtontotal)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlcard1Layout = new javax.swing.GroupLayout(pnlcard1);
        pnlcard1.setLayout(pnlcard1Layout);
        pnlcard1Layout.setHorizontalGroup(
            pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcard1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelform, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlcard1Layout.createSequentialGroup()
                        .addComponent(jPanel_info, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_info1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
        );
        pnlcard1Layout.setVerticalGroup(
            pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcard1Layout.createSequentialGroup()
                .addComponent(jPanelfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlcard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_info, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_info1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cardpanel.add(pnlcard1, "pnlcard1");

        pnlcard2.setBackground(new java.awt.Color(204, 204, 255));

        jPanelfile1.setBackground(new java.awt.Color(46, 49, 49));

        jLabel_filesearch1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_filesearch1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_filesearch1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_filesearch1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_filesearch1.setText("Search");
        jLabel_filesearch1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel_filesearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_filesearch1.setOpaque(true);
        jLabel_filesearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_filesearch1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_filesearch1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_filesearch1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelfile1Layout = new javax.swing.GroupLayout(jPanelfile1);
        jPanelfile1.setLayout(jPanelfile1Layout);
        jPanelfile1Layout.setHorizontalGroup(
            jPanelfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfile1Layout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(jLabel_filesearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        jPanelfile1Layout.setVerticalGroup(
            jPanelfile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfile1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel_filesearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelform1.setBackground(new java.awt.Color(0, 255, 255));
        jPanelform1.setLayout(new java.awt.GridBagLayout());

        jLabelbookeddetailsform.setBackground(new java.awt.Color(0, 0, 0));
        jLabelbookeddetailsform.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelbookeddetailsform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelbookeddetailsform.setText("Booked Details");
        jLabelbookeddetailsform.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 285, 11, 286);
        jPanelform1.add(jLabelbookeddetailsform, gridBagConstraints);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Mobile no", "Email", "Price", "Occupation", "Tour location", "No of days", "Tour date", "Booking date", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 255, 204));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout pnlcard2Layout = new javax.swing.GroupLayout(pnlcard2);
        pnlcard2.setLayout(pnlcard2Layout);
        pnlcard2Layout.setHorizontalGroup(
            pnlcard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelfile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlcard2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanelform1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(pnlcard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnlcard2Layout.setVerticalGroup(
            pnlcard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcard2Layout.createSequentialGroup()
                .addComponent(jPanelfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelform1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        cardpanel.add(pnlcard2, "pnlcard2");

        pnlcard3.setBackground(new java.awt.Color(255, 255, 255));
        pnlcard3.setPreferredSize(new java.awt.Dimension(844, 720));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        myreceipt4.setEditable(false);
        myreceipt4.setColumns(20);
        myreceipt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myreceipt4.setRows(5);
        jScrollPane7.setViewportView(myreceipt4);

        receipt_button4.setBackground(new java.awt.Color(51, 51, 51));
        receipt_button4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receipt_button4.setForeground(new java.awt.Color(255, 255, 255));
        receipt_button4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt_button4.setText("Print");
        receipt_button4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        receipt_button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        receipt_button4.setOpaque(true);
        receipt_button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receipt_button4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                receipt_button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                receipt_button4MouseExited(evt);
            }
        });

        jPanelform6.setBackground(new java.awt.Color(0, 255, 255));
        jPanelform6.setLayout(new java.awt.GridBagLayout());

        jLabelbookeddetailsform5.setBackground(new java.awt.Color(0, 0, 0));
        jLabelbookeddetailsform5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelbookeddetailsform5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelbookeddetailsform5.setText("Receipt");
        jLabelbookeddetailsform5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 285, 11, 286);
        jPanelform6.add(jLabelbookeddetailsform5, gridBagConstraints);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jScrollPane7)
                .addGap(277, 277, 277))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(receipt_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanelform6, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanelform6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(receipt_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanelfile3.setBackground(new java.awt.Color(46, 49, 49));

        jLabel_filesearch3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_filesearch3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_filesearch3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_filesearch3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_filesearch3.setText("Search");
        jLabel_filesearch3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jLabel_filesearch3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_filesearch3.setOpaque(true);
        jLabel_filesearch3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_filesearch3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_filesearch3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_filesearch3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelfile3Layout = new javax.swing.GroupLayout(jPanelfile3);
        jPanelfile3.setLayout(jPanelfile3Layout);
        jPanelfile3Layout.setHorizontalGroup(
            jPanelfile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfile3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_filesearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        jPanelfile3Layout.setVerticalGroup(
            jPanelfile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfile3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel_filesearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlcard3Layout = new javax.swing.GroupLayout(pnlcard3);
        pnlcard3.setLayout(pnlcard3Layout);
        pnlcard3Layout.setHorizontalGroup(
            pnlcard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelfile3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlcard3Layout.setVerticalGroup(
            pnlcard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcard3Layout.createSequentialGroup()
                .addComponent(jPanelfile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardpanel.add(pnlcard3, "pnlcard3");

        jSplitPane2.setRightComponent(cardpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseEntered
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel_dashboardMouseEntered

    private void jLabel_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseExited
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jLabel_dashboardMouseExited

    private void jDesktopPane_dashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane_dashMouseEntered
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jDesktopPane_dashMouseEntered

    private void jDesktopPane_dashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane_dashMouseExited
        // TODO add your handling code here:
        jDesktopPane_dash.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jDesktopPane_dashMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jLabel_bookingformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bookingformMouseClicked
        // TODO add your handling code here:
        cardLayout.show(cardpanel, "pnlcard1");
    }//GEN-LAST:event_jLabel_bookingformMouseClicked

    private void jLabel_bookingformMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bookingformMouseEntered
        // TODO add your handling code here:
        jLabel_bookingform.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel_bookingformMouseEntered

    private void jLabel_bookingformMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bookingformMouseExited
        // TODO add your handling code here:
        jLabel_bookingform.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jLabel_bookingformMouseExited

    private void jLabel2_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_sMouseClicked
        // TODO add your handling code here:
        cardLayout.show(cardpanel, "pnlcard3");
       

    }//GEN-LAST:event_jLabel2_sMouseClicked

    private void jLabel2_sMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_sMouseEntered
        // TODO add your handling code here:
        jLabel2_s.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel2_sMouseEntered

    private void jLabel2_sMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_sMouseExited
        // TODO add your handling code here:
        jLabel2_s.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jLabel2_sMouseExited

    private void jLabel3_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }//GEN-LAST:event_jLabel3_exitMouseClicked

    private void jLabel3_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_exitMouseEntered
        // TODO add your handling code here:
        jLabel3_exit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel3_exitMouseEntered

    private void jLabel3_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_exitMouseExited
        // TODO add your handling code here:
        jLabel3_exit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jLabel3_exitMouseExited

    private void jLabel1_bkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_bkMouseClicked
        // TODO add your handling code here:
        cardLayout.show(cardpanel, "pnlcard2");
        display();

    }//GEN-LAST:event_jLabel1_bkMouseClicked

    private void jLabel1_bkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_bkMouseEntered
        // TODO add your handling code here:
        jLabel1_bk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 55)));
    }//GEN-LAST:event_jLabel1_bkMouseEntered

    private void jLabel1_bkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_bkMouseExited
        // TODO add your handling code here:
        jLabel1_bk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
    }//GEN-LAST:event_jLabel1_bkMouseExited

    private void searchbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseClicked
        // TODO add your handling code here:

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchform().setVisible(true);
            }
        });

    }//GEN-LAST:event_searchbuttonMouseClicked

    private void searchbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonMouseEntered

    private void searchbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonMouseExited

    private void updatebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateik().setVisible(true);
            }
        });
    }//GEN-LAST:event_updatebuttonMouseClicked

    private void updatebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonMouseEntered

    private void updatebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebuttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttonMouseExited

    private void jRadioButtonmaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonmaleItemStateChanged
        // TODO add your handling code here:

        //        jRadioButtonmale.setActionCommand("male");
        //        jRadioButtonfemale.setActionCommand("female");

    }//GEN-LAST:event_jRadioButtonmaleItemStateChanged

    private void jRadioButtonmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmaleActionPerformed

    private void jRadioButtonfemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonfemaleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonfemaleItemStateChanged

    private void jRadioButtonfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonfemaleActionPerformed

    private void jTextField_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lnActionPerformed

    private void jTextField_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnActionPerformed

    private void jTextField_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mailActionPerformed

    private void jTextField_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numberActionPerformed

    private void jComboBox_occupationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_occupationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_occupationItemStateChanged

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButtonresetActionPerformed

          public void buttonvalidate()
        {
            if(jRadioButtonmale.isSelected())
            {
                gender = "Male";
            }
            else if(jRadioButtonfemale.isSelected())
            {
                gender = "Female";
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Please fill in all data");
            }
        }
          
    public void ik() {
        if (jTextField_fn.getText().equals("") 
            || jTextField_ln.getText().equals("") 
            || jTextField_number.getText().equals("") 
            || jTextField_mail.getText().equals("") 
            || jTextField_price.getText().equals("")
            || jComboBox_occupation.getSelectedItem().toString().equals("") 
            || jComboBox_tourlocation.getSelectedItem().toString().equals("") 
            || jComboBox_days.getSelectedItem().toString().equals("")
            || ((JTextField)jDatebookingdate.getDateEditor().getUiComponent()).getText().equals("")
            || buttonGroup1.isSelected(null)
            || ((JTextField)jDatebookeddate.getDateEditor().getUiComponent()).getText().equals("")) 
        {
            JOptionPane.showMessageDialog(this, "Please fill in all data");
        }
       buttonvalidate();
    }    
    
    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
        // TODO add your handling code here:

         ik();        
        if (evt.getSource() == jButtonsave) 
        {
            try 
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection("jdbc:sqlserver://IKAY\\MSSQLSERVERIK;databaseName=Library;user=sa;password=9815");
                //stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                stat = con.prepareStatement("INSERT INTO mynewtour VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                String tid = jTextField_id.getText().toLowerCase().trim();
                String tfn = jTextField_fn.getText().toLowerCase().trim();
                String tln = jTextField_ln.getText().toLowerCase().trim();
                Long tn  = Long.parseLong(jTextField_number.getText().toLowerCase().trim());
                String tmail = jTextField_mail.getText().toLowerCase().trim();
                int tprice = Integer.parseInt(jTextField_price.getText().trim());
                String toccu = jComboBox_occupation.getSelectedItem().toString();
                String ttlo = jComboBox_tourlocation.getSelectedItem().toString();
                String tdays = jComboBox_days.getSelectedItem().toString();
                String tbind = ((JTextField)jDatebookingdate.getDateEditor().getUiComponent()).getText();
                String tbed = ((JTextField)jDatebookeddate.getDateEditor().getUiComponent()).getText();
                //String tbgr = buttonGroup1.getSelection().getActionCommand().toString();
                String tbgr = gender.toLowerCase().trim();
                

                stat.setString(12, tid);
                stat.setString(1, tfn);
                stat.setString(2, tln);
                stat.setLong(3, tn);
                stat.setString(4, tmail);
                stat.setInt(5, tprice);
                stat.setString(6, toccu);
                stat.setString(7, ttlo);
                stat.setString(8, tdays);
                stat.setString(9, tbind);
                stat.setString(10, tbed);
                stat.setString(11, tbgr);

                stat.executeUpdate();
                
                receipt();
                display();

                JOptionPane.showMessageDialog(this, "Records have been saved");
                int n = JOptionPane.showConfirmDialog(this, "Do you want to add more records?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if (n == JOptionPane.YES_OPTION) 
                {
                    index++;
                    reset();
                    System.out.println(index);
                    System.out.println(newindex);
                } 
                else 
                {
                   reset();
                }
            } 
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_jButtonsaveActionPerformed

             public void receipt()
        {
            
                Calendar time = Calendar.getInstance();
                time.getTime();
                SimpleDateFormat mytime = new SimpleDateFormat("HH:mm:ss");
                String thetime =  mytime.format(time.getTime());

                  int num1;
                    String ref ="";
                    num1 = 1325 + (int)(Math.random()*4238);
                    ref += num1 + 1325;
            ////////////////////////////////////////////////////////////////////////////////////////////
            try {
                stat = con.prepareStatement("select Tourid from mynewtour where Tourfn=? ");
                stat.setString(1,jTextField_fn.getText());
                rs = stat.executeQuery();

                if (rs.next()) 
                {
                    String idno=rs.getString("Tourid");

                    String tfn = jTextField_fn.getText().toLowerCase().trim();
                    String tln = jTextField_ln.getText().toLowerCase().trim();
                    String tn = jTextField_number.getText().toLowerCase().trim();
                    String tmail = jTextField_mail.getText().toLowerCase().trim();
                    String tprice = jTextField_price.getText().trim();
                    String toccu = jComboBox_occupation.getSelectedItem().toString();
                    String ttlo = jComboBox_tourlocation.getSelectedItem().toString();
                    String tdays = jComboBox_days.getSelectedItem().toString();
                    String tbind = ((JTextField)jDatebookingdate.getDateEditor().getUiComponent()).getText();
                    String tbed = ((JTextField)jDatebookeddate.getDateEditor().getUiComponent()).getText();
                    //String tbgr = buttonGroup1.getSelection().getActionCommand().toString();
                    String tbgr = gender.toLowerCase().trim();


                    myreceipt4.append("\tPhoenix Tours \n\n"
                    + "Ref:\t" + ref
                    + "\nTime:\t" + thetime 
                    + "\nDate:\t" + tbind        
                    + "\n--------------------------------------------"
                    + "\nID:\t" + idno       
                    + "\nFirst Name:\t" + tfn
                    + "\nLast Name:\t"  + tln 
                    + "\nPhone number:\t" + tn 
                    + "\nEmail:\t" + tmail 
                    + "\nPrice:\t" + tfn 
                    + "\nFirst Name:\t" + tprice
                    + "\nOccupation:\t" + toccu 
                    + "\nTour Location:\t" + ttlo 
                    + "\nNumber of Days:" + tdays 
                    + "\nBooked date:\t" + tbed
                    + "\nGender:\t" + tbgr

                );
            }


            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

       }
    
    public void display()
        {
             //Display here
                //Displaying Records
        try
        { 
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection("jdbc:sqlserver://IKAY\\MSSQLSERVERIK;databaseName=Library;user=sa;password=9815");
                stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                stat = con.prepareStatement("select Tourid as 'ID', Tourfn as 'First Name', Tourln as 'Last Name', Tournumber as 'Mobile no', Tourmail as 'Email', TourPrice as 'Price', Touroccu as 'Occupation', Tourtlo as 'Tour Location', Tourdays as 'No of days', Tourbind as 'Booking Date', Tourbed as 'Tour Date', Tourbgr as 'Gender' from mynewtour");
                rs = stat.executeQuery();
               
                
                //data will be added until finish 
                while (rs.next()) 
                {
                
                String id = String.valueOf(rs.getInt("ID"));
                jTextField_id.setText(rs.getString("ID"));
                String fn = rs.getString("First Name");
                String ln = rs.getString("Last Name");
                String ntn = String.valueOf(rs.getLong("Mobile no"));
                String mail = rs.getString("Email");
                String price = String.valueOf(rs.getInt("Price"));
                String occu = rs.getString("Occupation");
                String tlo = rs.getString("Tour Location");
                String days = rs.getString("No of days");
                String bed = rs.getString("Tour Date");
                String bind = rs.getString("Booking Date");
                String bgr = rs.getString("Gender"); 
                


                 //string array to store data in jtable
                 String  data[] = {id, fn, ln, ntn, mail, price, occu, tlo, days, bed, bind, bgr};
                 jTable1.setEnabled(false);
                 jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                 DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
                 tblmodel.addRow(data);
                }
               //DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
                //tblmodel.addRow(data);
        } 
            
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "error in retrieving record");
        }
         
//        DefaultTableModel tblmodel = (DefaultTableModel)jTable1.getModel();
//        tblmodel.addRow(data);
        
        }

    public void reset() {
        jTextField_id.setText(null);
        jTextField_fn.setText(null);
        jTextField_ln.setText(null);
        jTextField_number.setText(null);
        jTextField_mail.setText(null);
        jTextField_price.setText(null);
        jComboBox_occupation.setSelectedIndex(0);
        jComboBox_tourlocation.setSelectedIndex(0);
        jComboBox_days.setSelectedIndex(0);
        jDatebookingdate.setCalendar(null);
        jDatebookeddate.setCalendar(null);
        buttonGroup1.clearSelection();
        

    }    
    
    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
        //        for (int i=1; i<101; i++)
        //        {
            //            if (index == 1) {
                //                String addtime = String.valueOf(index);
                //                jTextField_id.setText(addtime);
                //            }
            //        }
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_priceActionPerformed

    private void jComboBox_tourlocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocationItemStateChanged

    private void jComboBox_tourlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tourlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tourlocationActionPerformed

    private void jButtontotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtontotalMouseClicked
        // TODO add your handling code here:
        int eiffel = 150000;
        int pyramid = 200000;
        int statute = 180000;
        int ikogosi = 100000;
        int indian = 220000;
        int yankari = 120000;
        int trafford = 300000;
        int wembely = 300000;

        int days = 50000;
        int week = 100000;
        int weeks = 150000;
        int month = 200000;

        int result;

        //eiffel
        if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = eiffel + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = eiffel + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = eiffel + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Eiffel Tower")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = eiffel + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //pyramid
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = pyramid + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = pyramid + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = pyramid + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Pyramid of Giza")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = pyramid + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //statute
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = statute + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = statute + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = statute + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Statute of Liberty")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = statute + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //ikogosi
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = ikogosi + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = ikogosi + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = ikogosi + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Ikogosi water spring")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = ikogosi + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //indian ocean
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = indian + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = indian + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = indian + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Indian Ocean, Maldives")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = indian + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //yankari reserve
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = yankari + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = yankari + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = yankari + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Yankari game reserve")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = yankari + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //old trafford
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = trafford + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = trafford + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = trafford + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Old Trafford stadium")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = trafford + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } //wembely
        else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("3 days")) {
            result = wembely + days;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("1 week")) {
            result = wembely + week;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("2 weeks")) {
            result = wembely + weeks;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        } else if ((jComboBox_tourlocation.getSelectedItem().equals("Wembely stadium")) && jComboBox_days.getSelectedItem().equals("1 month")) {
            result = wembely + month;
            String total = String.valueOf(result);
            jTextField_price.setText(total);
        }
    }//GEN-LAST:event_jButtontotalMouseClicked

    private void jButtontotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtontotalActionPerformed

    private void jLabel_filesearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchform().setVisible(true);
            }
        });

    }//GEN-LAST:event_jLabel_filesearch1MouseClicked

    private void jLabel_filesearch1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch1MouseEntered

    private void jLabel_filesearch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch1MouseExited

    private void receipt_button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receipt_button4MouseClicked
        try {
            myreceipt4.print();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_receipt_button4MouseClicked

    private void receipt_button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receipt_button4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_receipt_button4MouseEntered

    private void receipt_button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receipt_button4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_receipt_button4MouseExited

    private void jLabel_filesearch3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch3MouseClicked

    private void jLabel_filesearch3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch3MouseEntered

    private void jLabel_filesearch3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_filesearch3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_filesearch3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JPanel cardpanel;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JButton jButtontotal;
    private javax.swing.JComboBox jComboBox_days;
    private javax.swing.JComboBox jComboBox_occupation;
    private javax.swing.JComboBox jComboBox_tourlocation;
    private com.toedter.calendar.JDateChooser jDatebookeddate;
    private com.toedter.calendar.JDateChooser jDatebookingdate;
    private javax.swing.JDesktopPane jDesktopPane_dash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel1_bk;
    private javax.swing.JLabel jLabel2_s;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_exit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_bookingform;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_filesearch1;
    private javax.swing.JLabel jLabel_filesearch3;
    private javax.swing.JLabel jLabel_gn1;
    private javax.swing.JLabel jLabelbookeddetailsform;
    private javax.swing.JLabel jLabelbookeddetailsform1;
    private javax.swing.JLabel jLabelbookeddetailsform2;
    private javax.swing.JLabel jLabelbookeddetailsform3;
    private javax.swing.JLabel jLabelbookeddetailsform5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_info;
    private javax.swing.JPanel jPanel_info1;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanelfile;
    private javax.swing.JPanel jPanelfile1;
    private javax.swing.JPanel jPanelfile3;
    private javax.swing.JPanel jPanelform;
    private javax.swing.JPanel jPanelform1;
    private javax.swing.JPanel jPanelform2;
    private javax.swing.JPanel jPanelform3;
    private javax.swing.JPanel jPanelform4;
    private javax.swing.JPanel jPanelform6;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JSplitPane jSplitPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_fn;
    private javax.swing.JTextField jTextField_id;
    public javax.swing.JTextField jTextField_ln;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_number;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextArea myreceipt;
    private javax.swing.JTextArea myreceipt1;
    private javax.swing.JTextArea myreceipt2;
    private javax.swing.JTextArea myreceipt4;
    private javax.swing.JPanel pnlcard1;
    public javax.swing.JPanel pnlcard2;
    private javax.swing.JPanel pnlcard3;
    private javax.swing.JLabel receipt_button;
    private javax.swing.JLabel receipt_button1;
    private javax.swing.JLabel receipt_button2;
    private javax.swing.JLabel receipt_button4;
    private javax.swing.JLabel searchbutton;
    private javax.swing.JLabel updatebutton;
    // End of variables declaration//GEN-END:variables
}
